### ISSUE TITLE
Accessible-dfa Font

### ISSUE THREAD

**Issue by denischene** [thibaudcolas/readability-group-survey#1]
### Subject of the feature

Accessible-dfa font

### Problem

Accessible-dfa font is a font dedicated to hard of seeing users and dyslexia users. But it is not included in this study.
https://github.com/Orange-OpenSource/font-accessible-dfa

### Expected behaviour

Please consider to ask authors to add Accessible-dfa font to the next study. 

### Alternatives

or at least please add a reference to it.

**Comment by thibaudcolas** [comment]
@denischene 👋 I had no involvement with this study so it’s not really my place to contact its authors to make suggestions. If you think this is a good suggestion please contact them yourself.
